name: Android Testing CI # <-- This is the name of the workflow
on: [ push ]

jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test report
        uses: asadmansr/android-test-report@v1.2.0 # <-- This is the action to run
        if: ${{ always() }} # <-- This is the condition to run this step